/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUInterfaces;

import Clases.SplashDesvanece;
import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import static java.lang.Thread.sleep;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.UIManager;

/**
 *
 * @author 
 */
public class GUISplashDesvanecedor extends javax.swing.JFrame {

    double i = 50, j = 1;
    SplashDesvanece hilo;
    private GUISplashDesvanecedor splashGUI = this;
    ImageIcon imagen = new ImageIcon();
    
    
    public GUISplashDesvanecedor() {
       this.setUndecorated(true);
        initComponents();
        AWTUtilities.setWindowOpaque(this, false);                        
        iniciarCarga();
        setLocationRelativeTo(null);
        progLogin.setVisible(false);
        setTitle("Iniciando sistema");     
        Image ico = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Recursos/LogoOK2019.png"));
        this.setIconImage(ico);
        progLogin.setVisible(false);
        AWTUtilities.setWindowOpaque(this, true);   
        
        
    }
    
//     private void starThread() {
//        Thread thread = new Thread(new Runnable() {
//            @Override
//            public void run() {
//                GUILogin gui = new GUILogin(splashGUI);
//                gui.setVisible(true);
//                gui.setLocationRelativeTo(null);
//                dispose();
//            }
//        });
//        thread.start();
//    }

//    public JProgressBar getProgressBar() {
//        return progLogin;
//    }
//
//    public JLabel getLabel() {
//        return lbllogin;
//    }
          
    public void iniciarCarga() {
        new Thread() {

            @Override
            public void run() {
                int i = 0;
                while (i <= 40) {
                    i++;
                    progLogin.setValue(i);
                    try {
                        sleep(40);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }

            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        progLogin = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        rSProgressMaterial1 = new rojerusan.componentes.RSProgressMaterial();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Fondo5.jpg"))); // NOI18N

        progLogin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                progLoginStateChanged(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("© Software realizado por Jose Ojeda. Todos los derechos reservados");
        jPanel1.add(jLabel4);

        rSProgressMaterial1.setAnchoProgress(5);

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSProgressMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSProgressMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(progLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(panelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void progLoginStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_progLoginStateChanged
        
       if (progLogin.getValue() == i) {
            if (j != 20) {
                AWTUtilities.setWindowOpacity(this, Float.valueOf((100 - j) / 150 + "f"));
                i++;
                j += 1;
            }
        }
        if (progLogin.getValue() == 20) {
            GUILogin v = new GUILogin();
            v.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_progLoginStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUISplashDesvanecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUISplashDesvanecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUISplashDesvanecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUISplashDesvanecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUISplashDesvanecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private javax.swing.JProgressBar progLogin;
    private rojerusan.componentes.RSProgressMaterial rSProgressMaterial1;
    // End of variables declaration//GEN-END:variables
// public javax.swing.JProgressBar getjProgressBar() {
//        return Progreso;
//    }
//}

    /**
     * @return the Progreso
     */
   /* public javax.swing.JProgressBar getProgreso() {
        return progLogin;
    }*/

    /**
     * @param Progreso the Progreso to set
     */
    /*public void setProgreso(javax.swing.JProgressBar Progreso) {
        this.progLogin = Progreso;
    }
}*/
    
    
    private void mustarCarga() {
        progreso().setForeground(new Color(0, 0, 0));
        progreso().setStringPainted(true);
    }

    public javax.swing.JProgressBar progreso() {
        return progLogin;
    }
}
