/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUInterfaces;

import Clases.Conexion;
import Clases.conectar;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

public class GUIUsuarios extends javax.swing.JFrame {

    DefaultTableModel model;
    TableColumnModel columnModel;

    public GUIUsuarios() {
        initComponents();
        Usuarios();
        Generarnumeracion();

        setLocationRelativeTo(null);

    }

    void limpiar() {
        txtnick.setText("");
        txtpass.setText("");

    }

    /**
     * *************************************************************************************************
     */
    void Generarnumeracion() {
        String SQL = "select max(idusuario) from tabla_usuarios";

        int c = 0;
        int b = 0;
        try {
            Statement st = Conexion.conexion().createStatement();
            ResultSet rs = st.executeQuery(SQL);
            while (rs.next()) {
                c = rs.getInt(1);
            }

            if (c == 0) {
                txtid.setText("1");
            } else {

                txtid.setText("" + (c + 1));

            }
        } catch (SQLException ex) {
            Logger.getLogger(GUIUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * **************************************************************************************************
     */
    void Usuarios() {
        String[] titulos = {"ID", "USUARIO", "PASS", "TIPO", "PREGUNTA", "RESPUESTA"};
        model = new DefaultTableModel(null, titulos);
        String datos[] = new String[6];
        String sql = "SELECT * FROM  tabla_usuarios";
        try {
            Statement st = Conexion.conexion().createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString("idusuario");
                datos[1] = rs.getString("nick");
                datos[2] = rs.getString("password");
                datos[3] = rs.getString("tipousuario");
                datos[4] = rs.getString("pregunta");
                datos[5] = rs.getString("respuesta");
                model.addRow(datos);
            }
            tabla_usuarios.setModel(model);

            txtcant.setText(" " + tabla_usuarios.getRowCount());

            tabla_usuarios.setAutoResizeMode(tabla_usuarios.AUTO_RESIZE_OFF);
            tabla_usuarios.setRowHeight(15);
            tabla_usuarios.getColumnModel().getColumn(0).setPreferredWidth(40);
            tabla_usuarios.getColumnModel().getColumn(1).setPreferredWidth(300);
            tabla_usuarios.getColumnModel().getColumn(2).setPreferredWidth(150);
            tabla_usuarios.getColumnModel().getColumn(3).setPreferredWidth(150);
            tabla_usuarios.getColumnModel().getColumn(4).setPreferredWidth(150);
            tabla_usuarios.getColumnModel().getColumn(5).setPreferredWidth(150);

        } catch (SQLException ex) {
            Logger.getLogger(GUIUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPopupMenu();
        mnmodificar = new javax.swing.JMenuItem();
        mneliminar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnick = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtpregunt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtrespuest = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_usuarios = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtcant = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        mnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ActualizarT.png"))); // NOI18N
        mnmodificar.setText("Actualizar registro");
        mnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnmodificarActionPerformed(evt);
            }
        });
        menu.add(mnmodificar);

        mneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/EliminarT.png"))); // NOI18N
        mneliminar.setText("Eliminar registro");
        mneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mneliminarActionPerformed(evt);
            }
        });
        menu.add(mneliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REGISTRO DE USUARIOS");
        setIconImage(new ImageIcon(getClass().getResource("/Recursos/Usuarios.png")).getImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Nuevo usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(4, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Id:");
        jLabel1.setPreferredSize(new java.awt.Dimension(10, 10));
        jPanel2.add(jLabel1);

        txtid.setEditable(false);
        txtid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtid);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Usuario:");
        jLabel2.setPreferredSize(new java.awt.Dimension(10, 10));
        jPanel2.add(jLabel2);

        txtnick.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtnick);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Password:");
        jLabel3.setPreferredSize(new java.awt.Dimension(10, 10));
        jPanel2.add(jLabel3);

        txtpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtpass);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Tipo Usuario:");
        jLabel4.setPreferredSize(new java.awt.Dimension(10, 10));
        jPanel2.add(jLabel4);

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[Seleccionar]", "Administrador", "Empleado", "Visitante" }));
        jPanel2.add(cbTipo);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Nuevos.png"))); // NOI18N
        jButton1.setToolTipText("Nuevo usuario");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Guardar.png"))); // NOI18N
        jButton2.setToolTipText("Guardar usuario");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Actualizar.png"))); // NOI18N
        jButton3.setToolTipText("Editar datos");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Regresar.png"))); // NOI18N
        jButton4.setToolTipText("Salir");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Pregunta de recuperación");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Respuesta");

        tabla_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla_usuarios.setComponentPopupMenu(menu);
        jScrollPane2.setViewportView(tabla_usuarios);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Total de registros:");

        txtcant.setEditable(false);
        txtcant.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtcant.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" REGISTRO DE USUARIOS");
        jPanel4.add(jLabel9);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtcant, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addComponent(txtpregunt, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtrespuest)))
                            .addComponent(jScrollPane2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpregunt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtrespuest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtcant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        limpiar();
        txtnick.requestFocus();
        jLabel3.setEnabled(true);
        txtpass.setEnabled(true);
        Generarnumeracion();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String id, nick, pass, tipo, preg, resp;
        String sql = "";
        id = txtid.getText();
        nick = txtnick.getText();
        pass = txtpass.getText();
        preg = txtpregunt.getText();
        resp = txtrespuest.getText();
        tipo = cbTipo.getSelectedItem().toString();

        String ins = "INSERT INTO tabla_usuarios (idusuario, nick, password, tipousuario,pregunta,respuesta) VALUES(?,?,?,?,?,?)";

        try {
            PreparedStatement pst = Conexion.conexion().prepareStatement(ins);
            pst.setString(1, id);
            pst.setString(2, nick);
            pst.setString(3, pass);
            pst.setString(4, tipo);
            pst.setString(5, preg);
            pst.setString(6, resp);
            int n = pst.executeUpdate();
            if (n > 0) {
                JOptionPane.showMessageDialog(this, "Usuario guardado con exito");
                Usuarios();

            } else {
                JOptionPane.showMessageDialog(this, "Error");
            }

        } catch (SQLException ex) {
            Logger.getLogger(GUIUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        /* USANDO VALIDACION MD5
        
         String id, nick, pass, tipo;
         String sql="";
         id=  txtid.getText();
         nick= txtnick.getText();
         pass= txtpass.getText();
         tipo= cbTipo.getSelectedItem().toString();

         String ins="INSERT INTO tabla_usuarios (idusuario, nick, password, tipousuario) VALUES(?,?,?,?)";
            
         try  {
         PreparedStatement pst = cn.prepareStatement(ins);
         pst.setString(1, id);
         pst.setString(2, nick);
         pst.setString(3,pass);
         pst.setString(4, tipo);
             
         if(md5(txtpass.getPassword()).equals(""))
         {
         JOptionPane.showMessageDialog(this, "Error");
         return;
         }
         pst.setString(3, md5(txtpass.getPassword()));
         int n= pst.executeUpdate();
         if(n>0){
                
         JOptionPane.showMessageDialog(this, "Regtrado");
         }
         Usuarios();

         } catch (SQLException ex) {
         Logger.getLogger(FRM_USUARIOS.class.getName()).log(Level.SEVERE, null, ex);

         /* USANDO VALIDACION MD5
        
         String id, nick, pass, tipo;
         String sql="";
         id=  txtid.getText();
         nick= txtnick.getText();
         pass= txtpass.getText();
         tipo= cbTipo.getSelectedItem().toString();

         String ins="INSERT INTO tabla_usuarios (idusuario, nick, password, tipousuario) VALUES(?,?,?,?)";
            
         try  {
         PreparedStatement pst = cn.prepareStatement(ins);
         pst.setString(1, id);
         pst.setString(2, nick);
         pst.setString(3,pass);
         pst.setString(4, tipo);
             
         if(md5(txtpass.getPassword()).equals(""))
         {
         JOptionPane.showMessageDialog(this, "Error");
         return;
         }
         pst.setString(3, md5(txtpass.getPassword()));
         int n= pst.executeUpdate();
         if(n>0){
                
         JOptionPane.showMessageDialog(this, "Regtrado");
         }
         Usuarios();

         } catch (SQLException ex) {
         Logger.getLogger(FRM_USUARIOS.class.getName()).log(Level.SEVERE, null, ex);
         }*/

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            PreparedStatement pst = Conexion.conexion().prepareStatement("UPDATE tabla_usuarios SET nick='" + txtnick.getText()
                    + "',password='" + txtpass.getText()//getPassword()
                    + "',tipousuario='" + cbTipo.getSelectedItem()
                    + "',pregunta='" + txtpregunt.getText()
                    + "',respuesta='" + txtrespuest.getText() + "' WHERE idusuario='" + txtid.getText() + "'");

            JOptionPane.showMessageDialog(null, "Datos actualizados correctamente");
            pst.executeUpdate();
            Usuarios();

        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void mnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnmodificarActionPerformed

        int filamodificar = tabla_usuarios.getSelectedRow();
        if (filamodificar >= 0) {
            txtid.setText(tabla_usuarios.getValueAt(filamodificar, 0).toString());
            txtnick.setText(tabla_usuarios.getValueAt(filamodificar, 1).toString());
            txtpass.setText(tabla_usuarios.getValueAt(filamodificar, 2).toString());
            cbTipo.setSelectedItem(tabla_usuarios.getValueAt(filamodificar, 3).toString());
            txtpregunt.setText(tabla_usuarios.getValueAt(filamodificar, 4).toString());
            txtrespuest.setText(tabla_usuarios.getValueAt(filamodificar, 5).toString());

        } else {
            JOptionPane.showMessageDialog(this, "No ha seleccionado");
        }

    }//GEN-LAST:event_mnmodificarActionPerformed

    private void mneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mneliminarActionPerformed

        try {

            int filas = tabla_usuarios.getSelectedRow();

            String desc = tabla_usuarios.getValueAt(filas, 1).toString();

            desc = tabla_usuarios.getValueAt(filas, 0).toString();

            int eliminar = JOptionPane.showConfirmDialog(null, "Desea eliminar este registro?", "Información", JOptionPane.YES_NO_OPTION);
            if (eliminar == 0) {

                PreparedStatement pst = Conexion.conexion().prepareStatement("DELETE FROM tabla_usuarios WHERE idusuario='" + desc + "'");

                JOptionPane.showMessageDialog(this, "Registro eliminado del sistema");
                pst.executeUpdate();
                Usuarios();

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Seleccione una fila de la tabla");
        }

    }//GEN-LAST:event_mneliminarActionPerformed


    /* public String md5(char [] c) {
     try {
     MessageDigest digest = MessageDigest.getInstance("MD5");

     digest.update((new String (c)).getBytes("UTF8"));
     String str = new String(digest.digest());
     return str;
            
     }  catch (Exception e) {
     return "";
     }
     }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu menu;
    private javax.swing.JMenuItem mneliminar;
    private javax.swing.JMenuItem mnmodificar;
    private javax.swing.JTable tabla_usuarios;
    private javax.swing.JTextField txtcant;
    public static javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnick;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtpregunt;
    private javax.swing.JTextField txtrespuest;
    // End of variables declaration//GEN-END:variables
//conectar cc = new conectar();
//    Connection cn = cc.conexion();
    String idfila = "";
}
