/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIConsultas;

import Clases.Conexion;
import Clases.ProductCaducidad;
import Clases.ReportsProdCad;
import Clases.conectar;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author
 */
public class GUI_CAlertas extends javax.swing.JFrame {

    DefaultTableModel model;

    public GUI_CAlertas() {
        initComponents();
        setLocationRelativeTo(null);
        ProductosAlertas("");

    }

    void ProductosAlertas(String valor) {
        String mostrar = "SELECT * FROM tabla_productos WHERE CONCAT(producto,codbarras) LIKE '%" + valor + "%'";
        String[] titulos = {"N°", "C.BARRAS", "PRODUCTO", "MARCA", "UNIDAD", "CATEGORIA", "P.COMP", "P,VENT", "STOCK", "F.CADUCIDAD", "IMAGEN"};
        String[] Datos = new String[11];
        model = new DefaultTableModel(null, titulos);

        try {
            Statement st = Conexion.conexion().createStatement();
            ResultSet rs = st.executeQuery(mostrar);
            while (rs.next()) {
                Datos[0] = rs.getString("codprod");
                Datos[1] = rs.getString("codbarras");
                Datos[2] = rs.getString("producto");
                Datos[3] = rs.getString("marca");
                Datos[4] = rs.getString("unidad");
                Datos[5] = rs.getString("categoria");
                Datos[6] = rs.getString("pre_compra");
                Datos[7] = rs.getString("pre_venta");
                Datos[8] = rs.getString("stock");
                Datos[9] = rs.getString("fechacaducidad");
                Datos[10] = rs.getString("imagen");

                model.addRow(Datos);
            }
            tbalertas.setModel(model);
            txtcant2.setText("" + tbalertas.getRowCount());
            tbalertas.setAutoResizeMode(tbalertas.AUTO_RESIZE_OFF);
            tbalertas.setRowHeight(22);
            tbalertas.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbalertas.getColumnModel().getColumn(1).setPreferredWidth(120);
            tbalertas.getColumnModel().getColumn(2).setPreferredWidth(320);
            tbalertas.getColumnModel().getColumn(3).setPreferredWidth(80);
            tbalertas.getColumnModel().getColumn(4).setPreferredWidth(80);
            tbalertas.getColumnModel().getColumn(5).setPreferredWidth(300);
            tbalertas.getColumnModel().getColumn(6).setPreferredWidth(80);
            tbalertas.getColumnModel().getColumn(7).setPreferredWidth(80);
            tbalertas.getColumnModel().getColumn(8).setPreferredWidth(100);
            tbalertas.getColumnModel().getColumn(9).setPreferredWidth(110);
            tbalertas.getColumnModel().getColumn(10).setPreferredWidth(300);
        } catch (SQLException ex) {
            Logger.getLogger(GUI_CAlertas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btcaducados = new javax.swing.JButton();
        btmedfalta = new javax.swing.JButton();
        btMenor10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtcant1 = new javax.swing.JTextField();
        txtcant2 = new javax.swing.JTextField();
        txtcant3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblimgalert = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbalertas = new rojerusan.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("INFORME DE CADUCIDADES Y STOCK");
        setIconImage(new ImageIcon(getClass().getResource("/Recursos/Alerta.png")).getImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btcaducados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Caducados.png"))); // NOI18N
        btcaducados.setText("Productos caducados");
        btcaducados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcaducadosActionPerformed(evt);
            }
        });

        btmedfalta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/90dias.png"))); // NOI18N
        btmedfalta.setText("Productos menores de 90 días");
        btmedfalta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmedfaltaActionPerformed(evt);
            }
        });

        btMenor10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Stock.png"))); // NOI18N
        btMenor10.setText("Productos en stock");
        btMenor10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenor10ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Total mínimo de 90 días:");

        txtcant1.setEditable(false);
        txtcant1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtcant1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtcant2.setEditable(false);
        txtcant2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtcant2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtcant3.setEditable(false);
        txtcant3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtcant3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Total de caducados:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Total de productos en stock:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PrintP.png"))); // NOI18N
        jButton1.setText("Imprimir reporte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Todos los productos deben ser retirados en caso de estar en Stock o ya Caducados");

        tbalertas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbalertas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbalertasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbalertas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btmedfalta, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btcaducados, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btMenor10, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtcant1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtcant2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtcant3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblimgalert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btcaducados)
                    .addComponent(btmedfalta)
                    .addComponent(btMenor10)
                    .addComponent(jButton1))
                .addGap(15, 15, 15)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblimgalert, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcant1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtcant2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtcant3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btcaducadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcaducadosActionPerformed
        String consult = "";
        consult = "SELECT `codprod`, `codbarras`, `producto`, `marca`, `unidad`, `categoria`, `pre_compra`, `pre_venta`,`stock`,"
                + " `fechacaducidad`,`imagen` FROM `tabla_productos` WHERE DATE(fechacaducidad) = DATE(NOW()) OR DATE(fechacaducidad) < DATE(NOW())";
        DefaultTableModel tabla = new DefaultTableModel();
        String[] titulos = {"N°", "C.BARRAS", "PRODUCTO", "MARCA", "UNIDAD", "CATEGORIA", "P.COMP", "P,VENT", "STOCK", "F.CADUCIDAD", "IMAGEN"};
        tabla.setColumnIdentifiers(titulos);
        this.tbalertas.setModel(tabla);

        String[] Datos = new String[11];
        try {
            Statement st = Conexion.conexion().createStatement();
            ResultSet rs = st.executeQuery(consult);
            while (rs.next()) {
                Datos[0] = rs.getString("codprod");
                Datos[1] = rs.getString("codbarras");
                Datos[2] = rs.getString("producto");
                Datos[3] = rs.getString("marca");
                Datos[4] = rs.getString("unidad");
                Datos[5] = rs.getString("categoria");
                Datos[6] = rs.getString("pre_compra");
                Datos[7] = rs.getString("pre_venta");
                Datos[8] = rs.getString("stock");
                Datos[9] = rs.getString("fechacaducidad");
                Datos[10] = rs.getString("imagen");

                tabla.addRow(Datos);
                txtcant2.setText("" + tbalertas.getRowCount());
                tbalertas.setAutoResizeMode(tbalertas.AUTO_RESIZE_OFF);
                tbalertas.setRowHeight(22);
                tbalertas.getColumnModel().getColumn(0).setPreferredWidth(50);
                tbalertas.getColumnModel().getColumn(1).setPreferredWidth(120);
                tbalertas.getColumnModel().getColumn(2).setPreferredWidth(320);
                tbalertas.getColumnModel().getColumn(3).setPreferredWidth(80);
                tbalertas.getColumnModel().getColumn(4).setPreferredWidth(80);
                tbalertas.getColumnModel().getColumn(5).setPreferredWidth(300);
                tbalertas.getColumnModel().getColumn(6).setPreferredWidth(80);
                tbalertas.getColumnModel().getColumn(7).setPreferredWidth(80);
                tbalertas.getColumnModel().getColumn(8).setPreferredWidth(100);
                tbalertas.getColumnModel().getColumn(9).setPreferredWidth(110);
                tbalertas.getColumnModel().getColumn(10).setPreferredWidth(300);

            }
        } catch (SQLException ex) {
            Logger.getLogger(GUI_CAlertas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btcaducadosActionPerformed

    private void btmedfaltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmedfaltaActionPerformed
        String consulta = "";
        consulta = "SELECT `codprod`, `codbarras`, `producto`, `marca`, `unidad`, `categoria`, `pre_compra`,`pre_venta`,`stock`,"
                + " `fechacaducidad`,`imagen` FROM `tabla_productos` WHERE DATE(fechacaducidad) = DATE(NOW()) OR DATE(fechacaducidad) < DATE(NOW()) OR DATEDIFF(fechacaducidad,NOW()) <= 90";

        DefaultTableModel tabla = new DefaultTableModel();
        String[] titulos = {"N°", "C.BARRAS", "PRODUCTO", "MARCA", "UNIDAD", "CATEGORIA", "P.COMP", "P.VENT", "STOCK", "F.CADUCIDAD", "IMAGEN"};
        tabla.setColumnIdentifiers(titulos);
        this.tbalertas.setModel(tabla);

        String[] Datos = new String[11];
        try {
            Statement st = Conexion.conexion().createStatement();
            ResultSet rs = st.executeQuery(consulta);
            while (rs.next()) {
                Datos[0] = rs.getString("codprod");
                Datos[1] = rs.getString("codbarras");
                Datos[2] = rs.getString("producto");
                Datos[3] = rs.getString("marca");
                Datos[4] = rs.getString("unidad");
                Datos[5] = rs.getString("categoria");
                Datos[6] = rs.getString("pre_compra");
                Datos[7] = rs.getString("pre_venta");
                Datos[8] = rs.getString("stock");
                Datos[9] = rs.getString("fechacaducidad");
                Datos[10] = rs.getString("imagen");

                tabla.addRow(Datos);
                txtcant1.setText("" + tbalertas.getRowCount());
                tbalertas.setAutoResizeMode(tbalertas.AUTO_RESIZE_OFF);
                tbalertas.setRowHeight(22);
                tbalertas.getColumnModel().getColumn(0).setPreferredWidth(50);
                tbalertas.getColumnModel().getColumn(1).setPreferredWidth(120);
                tbalertas.getColumnModel().getColumn(2).setPreferredWidth(320);
                tbalertas.getColumnModel().getColumn(3).setPreferredWidth(80);
                tbalertas.getColumnModel().getColumn(4).setPreferredWidth(80);
                tbalertas.getColumnModel().getColumn(5).setPreferredWidth(300);
                tbalertas.getColumnModel().getColumn(6).setPreferredWidth(80);
                tbalertas.getColumnModel().getColumn(7).setPreferredWidth(80);
                tbalertas.getColumnModel().getColumn(8).setPreferredWidth(100);
                tbalertas.getColumnModel().getColumn(9).setPreferredWidth(110);
                tbalertas.getColumnModel().getColumn(10).setPreferredWidth(300);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GUI_CAlertas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btmedfaltaActionPerformed

    private void btMenor10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenor10ActionPerformed

        String consulta = "";
        consulta = ("SELECT `codprod`, `codbarras`, `producto`, `marca`, `unidad`, `categoria`, `pre_compra`,`pre_venta`,`stock`,"
                + " `fechacaducidad`, `imagen` FROM `tabla_productos` WHERE stock <=10");

        DefaultTableModel tabla = new DefaultTableModel();

        String[] titulos = {"N°", "C.BARRAS", "PRODUCTO", "MARCA", "UNIDAD", "CATEGORIA", "P.COMP", "P,VENT", "STOCK", "F.CADUCIDAD", "IMAGEN"};
        tabla.setColumnIdentifiers(titulos);
        this.tbalertas.setModel(tabla);

        String[] Datos = new String[11];
        try {
            Statement st = Conexion.conexion().createStatement();
            ResultSet rs = st.executeQuery(consulta);
            while (rs.next()) {
                Datos[0] = rs.getString("codprod");
                Datos[1] = rs.getString("codbarras");
                Datos[2] = rs.getString("producto");
                Datos[3] = rs.getString("marca");
                Datos[4] = rs.getString("unidad");
                Datos[5] = rs.getString("categoria");
                Datos[6] = rs.getString("pre_compra");
                Datos[7] = rs.getString("pre_venta");
                Datos[8] = rs.getString("stock");
                Datos[9] = rs.getString("fechacaducidad");
                Datos[10] = rs.getString("imagen");

                tabla.addRow(Datos);
                txtcant3.setText("" + tbalertas.getRowCount());
                tbalertas.setAutoResizeMode(tbalertas.AUTO_RESIZE_OFF);
                tbalertas.setRowHeight(22);
                tbalertas.getColumnModel().getColumn(0).setPreferredWidth(50);
                tbalertas.getColumnModel().getColumn(1).setPreferredWidth(120);
                tbalertas.getColumnModel().getColumn(2).setPreferredWidth(320);
                tbalertas.getColumnModel().getColumn(3).setPreferredWidth(80);
                tbalertas.getColumnModel().getColumn(4).setPreferredWidth(80);
                tbalertas.getColumnModel().getColumn(5).setPreferredWidth(300);
                tbalertas.getColumnModel().getColumn(6).setPreferredWidth(80);
                tbalertas.getColumnModel().getColumn(7).setPreferredWidth(80);
                tbalertas.getColumnModel().getColumn(8).setPreferredWidth(100);
                tbalertas.getColumnModel().getColumn(9).setPreferredWidth(110);
                tbalertas.getColumnModel().getColumn(10).setPreferredWidth(300);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GUI_CAlertas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btMenor10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            ArrayList<ProductCaducidad> listacaduc = new ArrayList<ProductCaducidad>();
            int filas = tbalertas.getRowCount();
            for (int i = 0; i < filas; i++) {
                ProductCaducidad pcd = new ProductCaducidad(tbalertas.getValueAt(i, 0).toString(),
                        tbalertas.getValueAt(i, 1).toString(), tbalertas.getValueAt(i, 2).toString(),
                        tbalertas.getValueAt(i, 3).toString(), tbalertas.getValueAt(i, 4).toString(),
                        tbalertas.getValueAt(i, 5).toString(), tbalertas.getValueAt(i, 6).toString(),
                        tbalertas.getValueAt(i, 7).toString(), tbalertas.getValueAt(i, 8).toString(),
                        tbalertas.getValueAt(i, 9).toString(), tbalertas.getValueAt(i, 10).toString());
                listacaduc.add(pcd);
            }
            
            HashMap<String, Object> parametros = new HashMap<String, Object>();

            ReportsProdCad reports = new ReportsProdCad();
            
            if (reports.generarNuevoReporte("src//Reportes//R_Caducidades.jrxml", parametros, listacaduc)) {
                System.out.println("");
            } else {
                System.out.println("Error del Reporte");
                JOptionPane.showMessageDialog(null, "Error del Reporte");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error del Reporte" + ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbalertasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbalertasMouseClicked
        try {

            int filas = tbalertas.getSelectedRow();

            String prodimg = tbalertas.getValueAt(filas, 8).toString();

            String rut;

            rut = tbalertas.getValueAt(filas, 10).toString();

            try {
                int Fila = tbalertas.getSelectedRow();
                String Ruta;
                Ruta = lblimgalert.getText();
                String Imagen = tbalertas.getValueAt(Fila, 10).toString();
                ImageIcon img = new ImageIcon(Imagen);
                lblimgalert.setIcon(new ImageIcon(img.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH)));

            } catch (Exception e) {
                System.out.println("No hay imagen" + e);
            }

        } catch (Exception e) {
            System.out.println("Error" + e);
        }
    }//GEN-LAST:event_tbalertasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_CAlertas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_CAlertas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_CAlertas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_CAlertas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_CAlertas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMenor10;
    private javax.swing.JButton btcaducados;
    private javax.swing.JButton btmedfalta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblimgalert;
    private rojerusan.RSTableMetro tbalertas;
    private javax.swing.JTextField txtcant1;
    private javax.swing.JTextField txtcant2;
    private javax.swing.JTextField txtcant3;
    // End of variables declaration//GEN-END:variables
//conectar cc = new conectar();
//    Connection cn = cc.conexion();
}
