/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIConsultas;

import Clases.Conexion;
import Clases.Excel;
import Clases.Mensajes;
import Clases.conectar;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Usuario-Pc
 */
public class GUICCompras extends javax.swing.JFrame {

    DefaultTableModel table;
//    conectar cc = new conectar();
//    Connection cn = cc.conexion();
    private TableRowSorter trsFiltro;

    public GUICCompras() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("CONSULTA DE COMPRAS");
        Image ico = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Recursos/Buscar.png"));
        this.setIconImage(ico);
        Total();

    }

    void CargartodasFacturas() {
        DefaultTableModel tabla = new DefaultTableModel();
        String[] titulos = {"NUMERO", "PROVEEDOR", "DOCUMENTO", "SUBTOTAL", "IVA %", "TOTAL", "HORA", "FECHA EMISIÓN"};
        tabla.setColumnIdentifiers(titulos);
        this.tabla_compras.setModel(tabla);
        String consulta = "SELECT * FROM tabla_compras";
        String[] Datos = new String[8];
        try {
            Statement st = Conexion.conexion().createStatement();
            ResultSet rs = st.executeQuery(consulta);
            while (rs.next()) {
                Datos[0] = rs.getString("num_comp");
                Datos[1] = rs.getString("proveedor");
                Datos[2] = rs.getString("documento");
                Datos[3] = rs.getString("subtotal");
                Datos[4] = rs.getString("iva");
                Datos[5] = rs.getString("pre_tot");
                Datos[6] = rs.getString("hora");
                Datos[7] = rs.getString("fecha");

                tabla.addRow(Datos);
                tabla_compras.setAutoResizeMode(tabla_compras.AUTO_RESIZE_OFF);
                tabla_compras.setRowHeight(20);
                tabla_compras.getColumnModel().getColumn(0).setPreferredWidth(80);
                tabla_compras.getColumnModel().getColumn(1).setPreferredWidth(300);
                tabla_compras.getColumnModel().getColumn(2).setPreferredWidth(125);
                tabla_compras.getColumnModel().getColumn(3).setPreferredWidth(80);
                tabla_compras.getColumnModel().getColumn(4).setPreferredWidth(80);
                tabla_compras.getColumnModel().getColumn(5).setPreferredWidth(120);
                tabla_compras.getColumnModel().getColumn(6).setPreferredWidth(100);
                tabla_compras.getColumnModel().getColumn(7).setPreferredWidth(100);
                Total();
            }
        } catch (SQLException ex) {
            Logger.getLogger(GUICCompras.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void Total() {

        double sumatoria;
        double sumatoria1 = 0;
        double totalRow = tabla_compras.getRowCount();
        totalRow -= 1;
        for (int i = 0; i <= (totalRow); i++) {
            sumatoria = Double.parseDouble(String.valueOf(tabla_compras.getValueAt(i, 5)));
            sumatoria1 += sumatoria;
        }
        txtcomprast.setText(String.valueOf(sumatoria1));

    }

    public void RedondearTotComp() {
        double valor = Double.parseDouble(GUICCompras.txtcomprast.getText());
        String val = valor + "";
        BigDecimal big = new BigDecimal(val);
        big = big.setScale(2, RoundingMode.HALF_UP);
        System.out.println("Número : " + big);
        txtcomprast.setText("" + big);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_compras = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        rdbnnumero = new javax.swing.JRadioButton();
        txtnumero = new javax.swing.JTextField();
        rdbbnfecha = new javax.swing.JRadioButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        btnbuscador = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rdbntodos = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtcomprast = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabla_compras.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabla_compras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla_compras);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Opciones de busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        buttonGroup1.add(rdbnnumero);
        rdbnnumero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rdbnnumero.setSelected(true);
        rdbnnumero.setText("Mostrar Nº:");
        rdbnnumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdbnnumero.setOpaque(false);
        rdbnnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbnnumeroActionPerformed(evt);
            }
        });
        jPanel1.add(rdbnnumero);

        txtnumero.setBackground(new java.awt.Color(255, 204, 204));
        txtnumero.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtnumero.setText("Coloque Nº de compra");
        txtnumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnumeroMouseClicked(evt);
            }
        });
        jPanel1.add(txtnumero);

        buttonGroup1.add(rdbbnfecha);
        rdbbnfecha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rdbbnfecha.setText("Mostrar por Fecha");
        rdbbnfecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdbbnfecha.setOpaque(false);
        rdbbnfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbbnfechaActionPerformed(evt);
            }
        });
        jPanel1.add(rdbbnfecha);

        jDateChooser1.setOpaque(false);
        jPanel1.add(jDateChooser1);

        btnbuscador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Buscar.png"))); // NOI18N
        btnbuscador.setText("Buscar");
        btnbuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscadorActionPerformed(evt);
            }
        });
        jPanel1.add(btnbuscador);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Regresar2.png"))); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CONSULTA DE COMPRAS GENERALES GENERADAS A PROVEEDORES");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setOpaque(false);

        buttonGroup1.add(rdbntodos);
        rdbntodos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rdbntodos.setForeground(new java.awt.Color(0, 51, 204));
        rdbntodos.setText("Mostrar todas las compras");
        rdbntodos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdbntodos.setOpaque(false);
        rdbntodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbntodosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Total en compras:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ExcelG.png"))); // NOI18N
        jButton1.setText("Exportar a Excel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtcomprast.setEditable(false);
        txtcomprast.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtcomprast.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcomprast.setToolTipText("");
        txtcomprast.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtcomprast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcomprastMouseClicked(evt);
            }
        });
        txtcomprast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcomprastActionPerformed(evt);
            }
        });
        txtcomprast.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcomprastKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdbntodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtcomprast, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtcomprast))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbntodos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 937, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbnnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbnnumeroActionPerformed
        // TODO add your handling code here:
        if (rdbnnumero.isSelected() == true) {
            txtnumero.setEnabled(true);
            txtnumero.requestFocus();
            jDateChooser1.setDate(null);
            jDateChooser1.setEnabled(false);
            Total();
            RedondearTotComp();
        }
    }//GEN-LAST:event_rdbnnumeroActionPerformed

    private void txtnumeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnumeroMouseClicked
        txtnumero.setText("");
    }//GEN-LAST:event_txtnumeroMouseClicked

    private void rdbbnfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbbnfechaActionPerformed
        // TODO add your handling code here:
        if (rdbbnfecha.isSelected() == true) {
            jDateChooser1.setEnabled(true);
            txtnumero.setEnabled(false);
            txtnumero.setText("");
        }
    }//GEN-LAST:event_rdbbnfechaActionPerformed

    private void rdbntodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbntodosActionPerformed
        // TODO add your handling code here:
        if (rdbntodos.isSelected() == true) {
            jDateChooser1.setEnabled(false);
            jDateChooser1.setDate(null);
            txtnumero.setText("");
            txtnumero.setEnabled(false);
            CargartodasFacturas();
            Total();
            RedondearTotComp();
        }
    }//GEN-LAST:event_rdbntodosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JFileChooser dialog = new JFileChooser();
        int opcion = dialog.showSaveDialog(GUICCompras.this);

        if (opcion == JFileChooser.APPROVE_OPTION) {

            File dir = dialog.getSelectedFile();

            try {
                List<JTable> tb = new ArrayList<JTable>();
                tb.add(tabla_compras);

                Excel excelExporter = new Excel(tb, new File(dir.getAbsolutePath() + ".xls"));
                if (excelExporter.Export()) {

                    JOptionPane.showMessageDialog(null, "Tabla de compras exportada con èxito");
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }    

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnbuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscadorActionPerformed
        String num = txtnumero.getText();

        String consulta = "";
        if (rdbnnumero.isSelected() == true) {
            consulta = "SELECT * FROM tabla_compras WHERE num_comp='" + num + "'";
            Total();
            RedondearTotComp();
        }

        if (rdbbnfecha.isSelected() == true) {
            Date fecha = jDateChooser1.getDate();
            SimpleDateFormat formatofecha = new SimpleDateFormat("YYYY-MM-dd");
            String fec = "" + formatofecha.format(fecha);
            consulta = "SELECT * FROM tabla_compras WHERE fecha='" + fec + "'";
            Total();
            RedondearTotComp();
        }

        if (rdbntodos.isSelected() == true) {
            consulta = "SELECT * FROM tabla_compras ";

        }
        DefaultTableModel tabla = new DefaultTableModel();
        String[] titulos = {"NUMERO", "PROVEEDOR", "DOCUMENTO", "SUBTOTAL", "IVA %", "TOTAL", "HORA", "FECHA EMISIÓN"};
        tabla.setColumnIdentifiers(titulos);
        this.tabla_compras.setModel(tabla);

        String[] Datos = new String[8];
        try {
            Statement st = Conexion.conexion().createStatement();
            ResultSet rs = st.executeQuery(consulta);
            while (rs.next()) {
                Datos[0] = rs.getString("num_comp");
                Datos[1] = rs.getString("proveedor");
                Datos[2] = rs.getString("documento");
                Datos[3] = rs.getString("subtotal");
                Datos[4] = rs.getString("iva");
                Datos[5] = rs.getString("pre_tot");
                Datos[6] = rs.getString("hora");
                Datos[7] = rs.getString("fecha");

                tabla.addRow(Datos);
                tabla_compras.setAutoResizeMode(tabla_compras.AUTO_RESIZE_OFF);
                tabla_compras.setRowHeight(20);
                tabla_compras.getColumnModel().getColumn(0).setPreferredWidth(80);
                tabla_compras.getColumnModel().getColumn(1).setPreferredWidth(300);
                tabla_compras.getColumnModel().getColumn(2).setPreferredWidth(125);
                tabla_compras.getColumnModel().getColumn(3).setPreferredWidth(80);
                tabla_compras.getColumnModel().getColumn(4).setPreferredWidth(80);
                tabla_compras.getColumnModel().getColumn(5).setPreferredWidth(120);
                tabla_compras.getColumnModel().getColumn(6).setPreferredWidth(100);
                tabla_compras.getColumnModel().getColumn(7).setPreferredWidth(100);
                Total();
                RedondearTotComp();
            }
        } catch (SQLException ex) {
            Logger.getLogger(GUICCompras.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnbuscadorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtcomprastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcomprastActionPerformed

    }//GEN-LAST:event_txtcomprastActionPerformed

    private void txtcomprastKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcomprastKeyReleased

    }//GEN-LAST:event_txtcomprastKeyReleased

    private void txtcomprastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcomprastMouseClicked

    }//GEN-LAST:event_txtcomprastMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICCompras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscador;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdbbnfecha;
    private javax.swing.JRadioButton rdbnnumero;
    private javax.swing.JRadioButton rdbntodos;
    private javax.swing.JTable tabla_compras;
    public static javax.swing.JTextField txtcomprast;
    private javax.swing.JTextField txtnumero;
    // End of variables declaration//GEN-END:variables
}
