/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIConsultas;

import Clases.Conexion;
import Clases.Excel;
import Clases.Mensajes;
import Clases.conectar;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author
 */
public class GUICVentasDetalladas extends javax.swing.JFrame {

//    conectar cc = new conectar();
//    Connection cn = cc.conexion();

    public GUICVentasDetalladas() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("CONSULTA DE VENTAS DETALLADAS");
        Image ico = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Recursos/Buscar.png"));
        this.setIconImage(ico);
        CargartodasFacturas();
    }

    void CargartodasFacturas() {
        DefaultTableModel tabla = new DefaultTableModel();
        String[] titulos = {"NUMERO", "CLIENTE", "SUBTOTAL", "IVA %", "TOTAL", "F.PAGO", "HORA", "F.EMISIÓN"};
        tabla.setColumnIdentifiers(titulos);
        this.tbdetalles.setModel(tabla);
        String consulta = "SELECT * FROM tabla_ventas";
        String[] Datos = new String[8];
        try {
            Statement st = Conexion.conexion().createStatement();
            ResultSet rs = st.executeQuery(consulta);
            while (rs.next()) {
                Datos[0] = rs.getString("num_fact");
                Datos[1] = rs.getString("cliente");
                Datos[2] = rs.getString("subtotal");
                Datos[3] = rs.getString("iva");
                Datos[4] = rs.getString("total");
                Datos[5] = rs.getString("formapago");
                Datos[6] = rs.getString("hora");
                Datos[7] = rs.getString("fecha");

                tabla.addRow(Datos);
                tbdetalles.setAutoResizeMode(tbdetalles.AUTO_RESIZE_OFF);
                tbdetalles.setRowHeight(22);
                tbdetalles.getColumnModel().getColumn(0).setPreferredWidth(80);
                tbdetalles.getColumnModel().getColumn(1).setPreferredWidth(300);
                tbdetalles.getColumnModel().getColumn(2).setPreferredWidth(85);
                tbdetalles.getColumnModel().getColumn(3).setPreferredWidth(60);
                tbdetalles.getColumnModel().getColumn(4).setPreferredWidth(80);
                tbdetalles.getColumnModel().getColumn(5).setPreferredWidth(120);
                tbdetalles.getColumnModel().getColumn(6).setPreferredWidth(100);
                tbdetalles.getColumnModel().getColumn(7).setPreferredWidth(100);

            }
        } catch (SQLException ex) {
            Logger.getLogger(GUICVentas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void Total() {

        double sumatoria;
        double sumatoria1 = 0;
        double totalRow = tbdetalles.getRowCount();
        totalRow -= 1;
        for (int i = 0; i <= (totalRow); i++) {
            sumatoria = Double.parseDouble(String.valueOf(tbdetalles.getValueAt(i, 4)));
            sumatoria1 += sumatoria;
        }
        txtventa.setText(String.valueOf(sumatoria1));
        Calculos();
    }

    public void Calculos() {
        double gastos = Double.parseDouble(GUICVentasDetalladas.txtventa.getText());
        String valor = gastos + "";
        BigDecimal big = new BigDecimal(valor);
        big = big.setScale(2, RoundingMode.HALF_UP);
        System.out.println("Número : " + big);
        txtventa.setText("" + big);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rdbnnumero = new javax.swing.JRadioButton();
        txtnumero = new javax.swing.JTextField();
        rdbbnfecha = new javax.swing.JRadioButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbdetalles = new javax.swing.JTable();
        rdTodos = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtventa = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONSULTA GENERAL DE VENTAS - VENTAS Y CONSULTAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Opciones de busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        buttonGroup1.add(rdbnnumero);
        rdbnnumero.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rdbnnumero.setText("Mostrar Nº:");
        rdbnnumero.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        rdbnnumero.setOpaque(false);
        rdbnnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbnnumeroActionPerformed(evt);
            }
        });
        jPanel3.add(rdbnnumero);
        jPanel3.add(txtnumero);

        buttonGroup1.add(rdbbnfecha);
        rdbbnfecha.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rdbbnfecha.setText("Fecha:");
        rdbbnfecha.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        rdbbnfecha.setOpaque(false);
        rdbbnfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbbnfechaActionPerformed(evt);
            }
        });
        jPanel3.add(rdbbnfecha);

        jDateChooser1.setOpaque(false);
        jPanel3.add(jDateChooser1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Buscar.png"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Regresar2.png"))); // NOI18N
        jButton2.setText("Salir");
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        tbdetalles.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbdetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbdetalles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdetallesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbdetalles);

        buttonGroup1.add(rdTodos);
        rdTodos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rdTodos.setForeground(new java.awt.Color(0, 51, 204));
        rdTodos.setText("Todas la ventas");
        rdTodos.setOpaque(false);
        rdTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdTodosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Total:");

        txtventa.setEditable(false);
        txtventa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtventa.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Excel.png"))); // NOI18N
        jButton3.setText("Exportar a Excel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(rdTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtventa, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdTodos)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String num = txtnumero.getText();

        String consulta = "";
        if (rdbnnumero.isSelected() == true) {
            consulta = "SELECT * FROM tabla_ventas WHERE num_fact='" + num + "'";
            Total();
            Calculos();
        }

        if (rdbbnfecha.isSelected() == true) {
            Date fecha = jDateChooser1.getDate();
            SimpleDateFormat formatofecha = new SimpleDateFormat("YYYY-MM-dd");
            String fec = "" + formatofecha.format(fecha);
            consulta = "SELECT * FROM tabla_ventas WHERE fecha='" + fec + "'";
            Total();
            Calculos();
        }

        if (rdTodos.isSelected() == true) {
            consulta = "SELECT * FROM tabla_ventas ";

        }
        DefaultTableModel tabla = new DefaultTableModel();
        String[] titulos = {"NUMERO", "CLIENTE", "SUBTOTAL", "IVA %", "TOTAL", "F.PAGO", "HORA", "F.EMISIÓN"};
        tabla.setColumnIdentifiers(titulos);
        this.tbdetalles.setModel(tabla);

        String[] Datos = new String[8];
        try {
            Statement st = Conexion.conexion().createStatement();
            ResultSet rs = st.executeQuery(consulta);
            while (rs.next()) {
                Datos[0] = rs.getString("num_fact");
                Datos[1] = rs.getString("cliente");
                Datos[2] = rs.getString("subtotal");
                Datos[3] = rs.getString("iva");
                Datos[4] = rs.getString("total");
                Datos[5] = rs.getString("formapago");
                Datos[6] = rs.getString("hora");
                Datos[7] = rs.getString("fecha");

                tabla.addRow(Datos);
                tbdetalles.setAutoResizeMode(tbdetalles.AUTO_RESIZE_OFF);
                tbdetalles.setRowHeight(22);
                tbdetalles.getColumnModel().getColumn(0).setPreferredWidth(80);
                tbdetalles.getColumnModel().getColumn(1).setPreferredWidth(300);
                tbdetalles.getColumnModel().getColumn(2).setPreferredWidth(85);
                tbdetalles.getColumnModel().getColumn(3).setPreferredWidth(60);
                tbdetalles.getColumnModel().getColumn(4).setPreferredWidth(80);
                tbdetalles.getColumnModel().getColumn(5).setPreferredWidth(120);
                tbdetalles.getColumnModel().getColumn(6).setPreferredWidth(100);
                tbdetalles.getColumnModel().getColumn(7).setPreferredWidth(100);
                Total();
                Calculos();
            }
        } catch (SQLException ex) {
            Logger.getLogger(GUICVentas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rdbbnfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbbnfechaActionPerformed
        if (rdbbnfecha.isSelected() == true) {
            jDateChooser1.setEnabled(true);
            txtnumero.setEnabled(false);
            txtnumero.setText("");
        }
    }//GEN-LAST:event_rdbbnfechaActionPerformed

    private void rdbnnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbnnumeroActionPerformed
        if (rdbnnumero.isSelected() == true) {
            txtnumero.setEnabled(true);
            txtnumero.requestFocus();
            jDateChooser1.setDate(null);
            jDateChooser1.setEnabled(false);
            Total();
            Calculos();
        }
    }//GEN-LAST:event_rdbnnumeroActionPerformed

    private void rdTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdTodosActionPerformed
        if (rdTodos.isSelected() == true) {
            jDateChooser1.setEnabled(false);
            jDateChooser1.setDate(null);
            txtnumero.setText("");
            txtnumero.setEnabled(false);
            CargartodasFacturas();
            Total();
            Calculos();
        }
    }//GEN-LAST:event_rdTodosActionPerformed

    private void tbdetallesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdetallesMouseClicked
        int filasele = tbdetalles.getSelectedRow();

        GUICVentasDetalladasTotales an = new GUICVentasDetalladasTotales();
        an.setVisible(true);

        String numfac = tbdetalles.getValueAt(filasele, 0).toString();
        String cli = tbdetalles.getValueAt(filasele, 1).toString();
        String subtotal = tbdetalles.getValueAt(filasele, 2).toString();
        String iva = tbdetalles.getValueAt(filasele, 3).toString();
        String total = tbdetalles.getValueAt(filasele, 4).toString();
        String fecha = tbdetalles.getValueAt(filasele, 7).toString();

        GUICVentasDetalladasTotales.txtf.setText(numfac);
        GUICVentasDetalladasTotales.txtclientesf.setText(cli);
        GUICVentasDetalladasTotales.txtsubt.setText(subtotal);
        GUICVentasDetalladasTotales.txti.setText(iva);
        GUICVentasDetalladasTotales.lbltotalventas.setText("$" + total);
        GUICVentasDetalladasTotales.txtfecha.setText(fecha);

        DefaultTableModel model = (DefaultTableModel) GUICVentasDetalladasTotales.tbcancelar.getModel();
        String ver = "SELECT * FROM detalleventas WHERE num_fact='" + numfac + "'";
        String[] datos = new String[6];
        try {
            Statement st = Conexion.conexion().createStatement();
            ResultSet rs = st.executeQuery(ver);
            while (rs.next()) {
                datos[0] = rs.getString("num_fact");
                datos[1] = rs.getString("des_comp");
                datos[2] = rs.getString("cant_comp");
                datos[3] = rs.getString("pre_comp");
                datos[4] = rs.getString("descuento");
                datos[5] = rs.getString("pre_tot");
                model.addRow(datos);
            }
            GUICVentasDetalladasTotales.tbcancelar.setAutoResizeMode(GUICVentasDetalladasTotales.tbcancelar.AUTO_RESIZE_OFF);
            GUICVentasDetalladasTotales.tbcancelar.setRowHeight(22);
            GUICVentasDetalladasTotales.tbcancelar.getColumnModel().getColumn(0).setPreferredWidth(85);
            GUICVentasDetalladasTotales.tbcancelar.getColumnModel().getColumn(1).setPreferredWidth(300);
            GUICVentasDetalladasTotales.tbcancelar.getColumnModel().getColumn(2).setPreferredWidth(65);
            GUICVentasDetalladasTotales.tbcancelar.getColumnModel().getColumn(3).setPreferredWidth(65);
            GUICVentasDetalladasTotales.tbcancelar.getColumnModel().getColumn(4).setPreferredWidth(65);
            GUICVentasDetalladasTotales.tbcancelar.getColumnModel().getColumn(5).setPreferredWidth(65);
            GUICVentasDetalladasTotales.tbcancelar.setModel(model);

        } catch (SQLException ex) {
            Logger.getLogger(GUICVentasDetalladas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbdetallesMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       JFileChooser dialog = new JFileChooser();
        int opcion = dialog.showSaveDialog(GUICVentasDetalladas.this);
        if (opcion == JFileChooser.APPROVE_OPTION) {
            File dir = dialog.getSelectedFile();
            try {
                List<JTable> tb = new ArrayList<JTable>();
                tb.add(tbdetalles);

                Excel excelExporter = new Excel(tb, new File(dir.getAbsolutePath() + ".xls"));
                if (excelExporter.Export()) {
                    JOptionPane.showMessageDialog(null, "Ventas detalladas exportada con éxito");
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
        
        
        /*  try {
            List<JTable> tb = new ArrayList<JTable>();
            tb.add(tbdetalles);
            Excel excellExporter = new Excel(tb, new File("VENTAS DETALLADAS.xls"));
            if (excellExporter.Export()) {
                Mensajes.informacion("Datos exportados con èxito");
            }
            llamaExcel();
        } catch (Exception e) {
            System.out.println("No se pudo");
        }
    }

    public void llamaExcel() {
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "VENTAS DETALLADAS.xls");
        } catch (IOException e) {// } catch (Exception e) {
            System.out.println("No se pudo");
        }*/
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICVentasDetalladas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICVentasDetalladas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICVentasDetalladas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICVentasDetalladas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICVentasDetalladas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panel1;
    private javax.swing.JRadioButton rdTodos;
    private javax.swing.JRadioButton rdbbnfecha;
    private javax.swing.JRadioButton rdbnnumero;
    private javax.swing.JTable tbdetalles;
    private javax.swing.JTextField txtnumero;
    public static javax.swing.JTextField txtventa;
    // End of variables declaration//GEN-END:variables
}
